# Generated by Django 4.2.16 on 2024-11-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0004_recipeingredient_unique_recipes_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='raw_weight',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='weight',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='raw_weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
