# Generated by Django 4.2.16 on 2024-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0005_remove_ingredient_cost_remove_ingredient_raw_weight_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name',), name='unique ingredient name'),
        ),
    ]
