# Generated by Django 4.2.16 on 2024-11-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0006_ingredient_unique_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='desc',
        ),
    ]
