# Generated by Django 4.2.16 on 2024-11-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0007_rename_description_recipe_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desc',
            new_name='description',
        ),
    ]
