# Generated by Django 4.2.16 on 2024-11-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0009_favorite_favoriterecipe_favorite_favorites_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRecipe',
            new_name='FavoriteRecipes',
        ),
        migrations.RemoveConstraint(
            model_name='favoriterecipes',
            name='unique favorite recipes',
        ),
        migrations.RenameField(
            model_name='favoriterecipes',
            old_name='favorites',
            new_name='favorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_name',
            field=models.CharField(default='user', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipes',
            constraint=models.UniqueConstraint(fields=('favorite', 'recipe'), name='unique favorites recipes'),
        ),
    ]
