# Generated by Django 4.2.16 on 2024-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0010_rename_favoriterecipe_favoriterecipes_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user_name',), name='unique user name'),
        ),
    ]
