# Generated by Django 4.2.16 on 2024-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0011_favorite_unique_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='admin', max_length=300),
        ),
    ]
